export interface ToolDefinition {
  id: string;
  name: string;
  shortDescription: string;
  description: string;
  category: "JSON" | "Code & Diff" | "Encoders" | "Formatters" | "Converters";
  route: string;
  iconName: string;
  status: "active" | "planned";
  tags: string[];
}

export const TOOLS_REGISTRY: ToolDefinition[] = [
  {
    id: "json-viewer",
    name: "Online JSON Viewer",
    shortDescription: "Format, minify, inspect tree nodes, and validate JSON payload.",
    description: "Professional JSON inspector featuring beautifier, minifier, tree view node navigation, path copy, and 5MB file upload validation.",
    category: "JSON",
    route: "/json-viewer",
    iconName: "FileJson",
    status: "active",
    tags: ["json", "format", "minify", "tree", "validate", "inspector"],
  },
  {
    id: "json-compare",
    name: "Online JSON Compare",
    shortDescription: "Side-by-side JSON diff with auto-formatting and character tracking.",
    description: "Compare two JSON payloads with side-by-side highlighting. Features automatic formatting to ignore arbitrary whitespaces.",
    category: "JSON",
    route: "/json-compare",
    iconName: "FileJson",
    status: "active",
    tags: [
      "json compare",
      "json diff",
      "compare json",
      "online json compare",
      "json diff checker",
    ],
  },
  {
    id: "code-compare",
    name: "Online Text Compare",
    shortDescription: "Free Online Text Compare tool with side-by-side text & code diff checker.",
    description: "Professional Online Text Compare tool supporting side-by-side diffs, word and line difference highlighting, formatting actions, and complete browser privacy.",
    category: "Code & Diff",
    route: "/code-compare",
    iconName: "Code2",
    status: "active",
    tags: [
      "online text compare",
      "text compare",
      "text compare online",
      "text diff",
      "text difference",
      "code diff",
      "code difference",
      "online code compare",
      "compare code online",
      "diff checker",
      "side-by-side text diff",
      "online diff tool",
      "compare text online",
    ],
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    shortDescription: "Decode headers, payload, and verify signatures for JSON Web Tokens.",
    description: "Inspect JWT claims, expiration timestamps, and signature verification without transmitting secrets.",
    category: "Encoders",
    route: "/jwt-decoder",
    iconName: "KeyRound",
    status: "active",
    tags: ["jwt", "auth", "token", "decoder", "base64"],
  },
  {
    id: "online-translator",
    name: "Online Translator",
    shortDescription: "Accurate multi-language online text translator with auto-fallback engine.",
    description: "Instant free online text translation supporting 100+ languages, auto language detection, side-by-side view, character counter, and multi-engine failover.",
    category: "Converters",
    route: "/translator",
    iconName: "Languages",
    status: "active",
    tags: [
      "online translator",
      "free translator online",
      "text translate",
      "language converter",
      "multi language translator",
      "auto detect language",
    ],
  },
  {
    id: "code-playground",
    name: "Online Code Editor",
    shortDescription: "Write, compile, and execute code in multiple languages online.",
    description: "Professional online code editor supporting syntax highlighting, multiple languages (JavaScript, Python, C++, Java, etc.), and instant cloud execution.",
    category: "Code & Diff",
    route: "/online-code-editor",
    iconName: "Terminal",
    status: "active",
    tags: [
      "online code editor",
      "code playground",
      "compile online",
      "execute code",
      "javascript online",
      "python compiler",
    ],
  },
  {
    id: "currency-converter",
    name: "Online Currency Converter",
    shortDescription: "Real-time exchange rates and multi-currency conversions.",
    description: "Professional online currency converter featuring real-time live exchange rates, historical fallback data, and an intuitive UI for global finance calculations.",
    category: "Converters",
    route: "/currency-converter",
    iconName: "Banknote",
    status: "active",
    tags: [
      "currency converter",
      "exchange rates",
      "online currency converter",
      "live exchange rates",
      "fiat converter",
    ],
  },
  {
    id: "image-tools",
    name: "Online Image Tools Hub",
    shortDescription: "Convert, compress, and resize images instantly with high quality.",
    description: "Professional online image tools. Convert PNG to JPG, compress image size, resize graphics, and process transparent images directly in your browser with high performance.",
    category: "Converters",
    route: "/image-tools",
    iconName: "Sparkles",
    status: "active",
    tags: [
      "image converter",
      "png to jpg",
      "jpg to png",
      "image resizer",
      "image compressor",
      "transparent imager",
      "webp converter"
    ],
  },
  {
    id: "document-tools",
    name: "Online Document Tools Hub",
    shortDescription: "Merge PDFs, convert Excel to CSV, and organize files.",
    description: "Professional online document tools. Merge multiple PDFs, split PDF pages, convert Excel files to CSV, and merge multiple spreadsheets effortlessly and securely in your browser.",
    category: "Converters",
    route: "/document-tools",
    iconName: "FileText",
    status: "active",
    tags: [
      "merge pdf",
      "split pdf",
      "excel to csv",
      "merge excel",
      "pdf tools",
      "document tools"
    ],
  },
  {
    id: "find-my-ip",
    name: "Find My IP Address",
    shortDescription: "Check your public IP address, geolocation, and ISP instantly.",
    description: "Detect your public IPv4/IPv6 address securely. Provides detailed network information including geolocation (city, country), ISP details, and ASN without logging your data.",
    category: "Encoders",
    route: "/find-my-ip",
    iconName: "Globe",
    status: "active",
    tags: [
      "what is my ip",
      "find my ip",
      "ip checker",
      "ip address location",
      "public ip",
      "ipv4 address"
    ],
  },
  {
    id: "base64-converter",
    name: "Base64 Encoder & Decoder",
    shortDescription: "Encode text to Base64 or decode Base64 back to plain text instantly.",
    description: "Fast, secure, and privacy-focused Base64 encoding and decoding utility. Operates completely client-side in real-time with full UTF-8 character support.",
    category: "Encoders",
    route: "/base64-converter",
    iconName: "Binary",
    status: "active",
    tags: [
      "base64 encoder",
      "base64 decoder",
      "base64 converter",
      "encode base64",
      "decode base64",
      "base64 string"
    ],
  },
  {
    id: "weather",
    name: "Online Weather & Forecast",
    shortDescription: "Check live local weather conditions and multi-day forecasts for any area.",
    description: "Instantly detect your local weather or search for any city, state, or country worldwide to view live temperature, humidity, wind speed, and accurate 4-day forecasts.",
    category: "Converters",
    route: "/weather",
    iconName: "CloudSun",
    status: "active",
    tags: [
      "weather",
      "forecast",
      "local weather",
      "live weather",
      "weather checker"
    ],
  },
];


